language: ruby
rvm: 2.2.5
install:
  - gem install awestruct bootstrap-sass haml-contrib maruku
script:
  - awestruct -P production
before_deploy:
  - npm i netlify-cli
  - ( cd _site && zip -r ../site.zip * )
deploy:
  provider: script
  skip_cleanup: true
  script:
    - node_modules/.bin/netlify deploy -s www-togglz-org -t $ACCESS_TOKEN -p site.zip
  on:
    repo: togglz/togglz-site
    branch: master
env:
  global:
    secure: gLlQaGDzWPYgKI4CPo0C2HPJMNMWCgfK6bKYQ23renvXkYuqkExHcDJt9kUPsMsF4F4dUCDy93dzsca0foa0zHyqXqCVeYcP9e8IfSxRtdlBPmkeUkn6EImbG6pqmhVJZrOpwnfnCwY6A/DhSnkWDM5BBe/VQ7a1ClctO9kxZgA=
