stableVersion: 1.1.0.Final
developmentVersion: 1.2.0-SNAPSHOT
jdkJavadocsBase: http://docs.oracle.com/javase/7/docs/api
profiles:
  development:
  production:
    base_url: http://www.togglz.org/
    google_analytics: UA-7295879-8
    deploy:
      host: www.togglz.org
      path: /home/www/togglz.org/htdocs
