stableVersion: 2.4.1.Final
developmentVersion: 2.5.0-SNAPSHOT
jdkJavadocsBase: http://docs.oracle.com/javase/7/docs/api
profiles:
  development:
    showBuildStatus: false
  production:
    base_url: http://www.togglz.org/
    google_analytics:
      account: UA-7295879-8
    showBuildStatus: true
